#ifndef ObjData_H
#define ObjData_H
const char* enemies[] = {
	"Aquaball",
	"Batabata",
	"Beeton",
	"EggRobo",
	"Ganigani",
	"Grabber",
	"Helicopter",
	"Lander",
	"Motora",
	"Tank",
	"EnemySpawner",
	"Bommer",
	"Bubble",
	"Defender",
	"Jellyman",
	"Jumper",
	"JumperSub",
	"Robber",
	"Sniper",
	"Territory",
	"Twister",
	"Umbrella",
	"Wolf",
	"WolfManager",
	"Bird",
	"MiniBossSpawner",
	"Blade",
	"Daruma",
	"Charger",
	"Spider",
	"Flyer",
	"Tracker",
	"Ashura",
	"Tyrant",
	"Sumo",
	"Strider",
	"Warship",
	"Giant",
	"Dragon",
	"Knight",
	"Rifle",
	"TheEnd"
};
const char* include[] = {
	"Ring",
	"SuperRing",
	"Kodama",
	"KodamaNewForm",
	"MusicMemory"
	"Path",
	"PathCircle",
	"PathConnector",
	"PathLine",
	"PathLoop",
	"PathNode",
	"PathPolygon",
	"PathSpiral",
	"AirFloor",
	"AirWall",
	"Balloon",
	"Spring",
	"SequenceItem",
	"PortalBit",
	"StorageKey",
	"TreasureChest",
	"FishCoin",
	"PowerupSeed",
	"DashPanel",
	"JumpBoard",
	"Fan",
	"IslandSpring",
	"IslandUpReel",
	"UpReel",
	"Pulley",
	"PulleyColumn",
	"DashRing",
	"GrindBooster",
	"TwoWayGrindBooster",
	"DashRoller",
	"WallJumpBlock",
	"GimmickInfo",
	"SlashCommon",
	"GuideLight"
};
const char* collectibles[] = {
	"SequenceItem",
	"PortalBit",
	"StorageKey",
	"TreasureChest",
	"FishCoin",
	"PowerupSeed",
};
const char* cameraTriggers[] = {
	"CameraVolume",
	"CameraVolumeOnce",
	"CameraVolumeSub",
};
const char* dashPanels[] = {
	"DashPanel",
	"GrindBooster",
	"TwoWayGrindBooster",
	"DashRoller"
};
const char* dimensionVolumes[] = {
	"DimensionVolume",
};
const char* springs[] = {
	"Spring",
	"SpringEgg",
	"DragonRoadSpring",
	"SpiderSpring"
};
const char* excludeFromStability[] = {
	"Path",
	"PathCircle",
	"PathConnector",
	"PathLine",
	"PathLoop",
	"PathNode",
	"PathPolygon",
	"PathSpiral",
	"AirFloor",
	"AirWall"
};
#endif